<a href="https://colab.research.google.com/github/beingshub02/25_days_of_Ml/blob/main/ML_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Loading Data**
**Day 2**

**2.1 Loading a Sample Dataset**



*   Probelm
*   You want to load a preexisting sample dataset for you to see:

In [1]:
# Load scikit-learn's dataset
from sklearn import datasets

# Load digits dataset
digits = datasets.load_digits()

# Create features matrix
features = digits.data

# Create target vector
target = digits.target

# View first observation
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

**2.2 Creating a Simulated Dataset**

*   Problem
*   You need to generate a dataset of simulated data.

In [3]:
# Load library
from sklearn.datasets import make_regression

# Generate features matrix, target vector , and the true coefficients
features, target, coefficients = make_regression(n_samples = 100,
                                                   n_features = 3,
                                                   n_informative = 3,
                                                   n_targets = 1,
                                                   noise = 0.0,
                                                   coef = True,
                                                   random_state= 1)

# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]

**2.3 Loading a CSV File**

*   Problem
*   You need to import a comma-seperated value (CSV) file.

In [7]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# View first two rows
dataframe.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

**2.4 Loading an Excel File**


*   Problem
*   You need to import an Excel spreadsheet.

In [10]:
# Load library
import pandas as pd

# Create URL
url = '/content/titanic.xlsx'

# Load data
dataframe = pd.read_excel(url, sheet_name=0, header=0)

# View the first two rows
dataframe.head(2)

# View the first two rows
dataframe.head(2)

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Haghish, E. F.",male,30.0,0,0,24058,26.5500,A1 Special,S,1,NaN,"Odense, Denmark"
1,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"

**2.5 Loading a JSON File**

*   Problem
*   You need to load a JSON file for data preprocessing.

In [11]:
# Load library
import pandas as pd

# Create URL
url = '/content/Titanic.json'

# Load data
dataframe = pd.read_json(url, orient='columns')

# View the first two rows
dataframe.head(2)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.55,C22 C26,S,11,,"Montreal, PQ / Chesterville, ON"

**2.6 Loading a Praquet File**



*   Problem
*   You need to load a Parquet file.

In [12]:
# Load library
import pandas as pd

# Create URL
url = '/content/titanic.parquet'

# Load data
dataframe = pd.read_parquet(url)

# View the first two rows
dataframe.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C